sudo: required
services:
  - docker

before_install:
  - docker build -t mikulass/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mikulass/react-test npm run test -- --coverage

after_success:
  - docker build -t mikulass/multi-client ./client
  - docker build -t mikulass/multi-nginx ./nginx
  - docker build -t mikulass/multi-server ./server
  - docker build -t mikulass/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  # Login
  - docker push mikulass/multi-client
  - docker push mikulass/multi-nginx
  - docker push mikulass/multi-server
  - docker push mikulass/multi-worker